version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'jdroll'
      MYSQL_USER: 'jdroll'
      MYSQL_PASSWORD: 'devdev'
      MYSQL_ROOT_PASSWORD: 'devdev'
    command: --sql_mode=""
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - jdroll-db:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/data.sql:/sql/data.sql:ro
      - ./docker/load-data.sh:/sql/load-data.sh:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  php:
    build: ./
    links:
      - db
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./:/code
  web:
    image: nginx:1.19.8-alpine
    links:
      - php
    volumes:
      - ./web.conf:/etc/nginx/conf.d/default.conf
      - ./:/code
    ports:
      - "8080:80"
volumes:
  jdroll-db: